import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/userDataCookie";

const InterFont = Inter({
  subsets: ["latin"],
  variable: "--Inter",
});

const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--Poppins",
});

export const metadata: Metadata = {
  title: "E-Learning School",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InterFont.variable} ${PoppinsFont.variable} antialiased`}
      >
        <UserProvider>
          <div className="m-auto max-w-[32rem] h-screen w-full bg-white">
            {children}
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
